import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: " biquíni básico fio - Roxo",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 79.99,
    images: ["/images/Roxo.jpg"],
    category: "Biquinis",
    sizes: ["M",],
    colors: ["#A020F0"],
    isNew: true,
    stock: 0,
  },
  {
    id: "2",
    name: "Cortininha fio c/argola - Off White",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 84.99,
    images: ["/images/offwhite.jpg"],
    category: "Biquinis",
    sizes: ["P","M","G"],
    colors: ["#FAF9F6"],
    isNew: true,
    stock: 0,
  },
  {
    id: "3",
    name: " Básico empina bumbum - Café",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 79.99,
    images: ["/images/cafe.jpg"],
    category: "Biquinis",
    sizes: ["P","M","G"],
    colors: ["#514240"],
    isNew: true,
    stock: 0,
  },
  {
    id: "4",
    name: "Básico Empina Bumbum - Amarelo",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 79.99,
    images: ["/images/amarelo.jpg"],
    category: "Biquinis",
    sizes: ["P","M"],
    colors: ["#ffff00"],
    isNew: true,
    stock: 1,
  },
  {
    id: "5",
    name: "Biquíni Básico - Azul Cristal",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 79.99,
    images: ["/images/AzulCristal.jpg"],
    category: "Biquinis",
    sizes: ["P"],
    colors: ["#C8E5EB"],
    isNew: true,
    stock: 1,
  },
];