import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: " Modelo Maré - Roxo",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 79.99,
    images: ["/images/roxo2.jpg"],
    category: "Biquinis",
    sizes: ["M",],
    colors: ["#A020F0"],
    isNew:  false,
    stock: 0,
  },
  {
    id: "2",
    name: "Modelo Sol - Off White",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 84.99,
    images: ["/images/offwhite.jpg"],
    category: "Biquinis",
    sizes: ["P","M","G"],
    colors: ["#FAF9F6"],
    isNew:  false,
    stock: 0,
  },
  {
    id: "3",
    name: " Modelo Areia - Café",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 79.99,
    images: ["/images/cafe.jpg"],
    category: "Biquinis",
    sizes: ["P","M","G"],
    colors: ["#514240"],
    isNew: false,
    stock: 0,
  },
  {
    id: "4",
    name: "Modelo Areia - Amarelo",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 64.99,
    images: ["/images/amarelo.jpg"],
    category: "Biquinis",
    sizes: ["P",],
    colors: ["#ffff00"],
    isNew: true,
    stock: 0,
  },
  {
    id: "5",
    name: "Modelo Coral - Azul Cristal",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 64.99,
    images: ["/images/AzulCristal.jpg"],
    category: "Biquinis",
    sizes: ["P"],
    colors: ["#C8E5EB"],
    isNew: false,
    stock: 0,
  },
  {
    id: "6",
    name: "Modelo Jasmin - Rosa bebê",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n",
    price: 64.99,
    images: ["/images/rosabb.jpg"],
    category: "Biquinis",
    sizes: ["M"],
    colors: ["#FF69B4"],
    isNew: true,
    stock: 0,
  },
  {
    id: "7",
    name: "Modelo Ibiza - Azul Royal",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 64.99,
    images: ["/images/azulroyal1.jpg"],
    category: "Biquinis",
    sizes: ["M"],
    colors: ["#4169e1"],
    isNew: true,
    stock: 0,
  },
  {
    id: "8",
    name: "Modelo Aurora - Roxo",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n",
    price: 84.99,
    images: ["/images/Roxo1.jpg"],
    category: "Biquinis",
    sizes: ["M"],
    colors: ["#A020F0"],
    isNew: true,
    stock: 1, 
  },
  {
    id: "9",
    name: "Modelo Aurora - Marrom",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n",
    price: 84.99,
    images: ["/images/marrom1.jpg"],
    category: "Biquinis",
    sizes: ["G"],
    colors: ["#5b3c1d"],
    isNew: true,
    stock: 1,
  },
  {
    id: "10",
    name: "Modelo laguna - Cappuccino",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 59.99,
    images: ["/images/marrom2.jpg"],
    category: "Biquinis",
    sizes: ["M"],
    colors: ["#5b3c1d"],
    isNew: true,
    stock: 0,
  },
  {
    id: "11",
    name: "Modelo Rio - Vermelho",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças e Calcinha reguláveis",
    price: 59.99,
    images: ["/images/vermelho.jpg"],
    category: "Biquinis",
    sizes: ["M"],
    colors: ["#FF0000"],
    isNew: true,
    stock: 0,
  },
  {
    id: "12",
    name: "Modelo luar - Preto",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n- Alças reguláveis",
    price: 84.99,
    images: ["/images/preto.jpg"],
    category: "Biquinis",
    sizes: ["M"],
    colors: ["#000000"],
    isNew: true,
    stock: 0,
  },
  {
    id: "13",
    name: "Modelo Aurora - Azul Royal",
    description: "Tecido Beach Gloss com FPS 50\n- Acompanha bojo removível e saquinho\n- P 36/38 M 38/40 G 40/42\n",
    price: 84.99,
    images: ["/images/azulroyal2.jpg"],
    category: "Biquinis",
    sizes: ["M"],
    colors: ["#4169e1"],
    isNew: true,
    stock: 0,
    },
    {
    id: "14",
    name: "Saia baladinha com stass",
    description: "",
    price: 59.99,
    images: ["/images/saiabaladinha.jpg"],
    category: "Vestuario",
    sizes: ["M"],
    colors: ["#000000"],
    isNew: true,
    stock: 0,
    },
    {
    id: "15",
    name: "Bata",
    description: "- Tamanho único (P/M/G)\n- Disponível na cor Laranja Telha",
    price: 39.99,
    images: ["/images/bata.jpg"],
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#E2725B"],
    isNew: true,
    stock: 0,
    },
    {
    id: "16",
    name: "Vestido Laura",
    description: "- Tamanho único (P/M/G)",
    price: 84.99,
    images: ["/images/vestidolaura.jpg"],
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#E2725B"],
    isNew: true,
    stock: 0,
    },
    {
    id: "17",
    name: "Conjuto Melissa - Nude",
    description: "- Tamanho único (P/M/G)",
    price: 84.99,
    images: ["/images/conjuntomelissa-nude.jpg"],
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#ebc8b2"],
    isNew: true,
    stock: 0,
    },
    {
    id: "18",
    name: "Conjuto Melissa - Cinza",
    description: "Tamanho único (P/M/G)",
    price: 84.99,
    images: ["/images/conjuntomelissa-cinza.jpg"],
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#808080"],
    isNew: true,
    stock: 0,
    },
    {
    id: "19",
    name: "Conjuto Carmem",
    description: "- Tecido leve e confortável\n- Tamanho único (P/M/G)",
    price: 99.99,
    images: ["/images/conjuntocarmem.jpg"],
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#000000"],
    isNew: true,
    stock: 0,
    },
    {
    id: "20",
    name: "Macaquinho",
    description: "- Tecido leve e confortável\n- Tamanho único (P/M/G)",
    price: 109.99,
    images: ["/images/macaquinho-preto.jpg"],
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#000000"],
    isNew: true,
    stock: 0,
    },
    {
    id: "21",
    name: "Conjunto festa",
    description: "- Tecido leve e confortável\n- Tamanho único (P/M/G)",
    price: 84.99,
    images: ["/images/conjuntofesta.jpg"],
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#000000"],
    isNew: true,
    stock: 0,
    },
    {
    id: "22",
    name: "Vestido Maju",
    description: "- Tamanho único (P/M/G)",
    price: 44.99,
    images: ["/images/vestidomaju2.jpg"],
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#ebc8b2"],
    isNew: true,
    stock: 1,
    },
    {
    id: "23",
    name: "body - Preto",
    description: "- Tamanho único (P/M/G)",
    price: 44.99,
    images: ["/images/body-preto.jpg"], 
    category: "Vestuario",
    sizes: ["M"],
    colors: ["#000000"],
    isNew: true,
    stock: 0,
    },
    {
    id: "24",
    name: "body - Nude",
    description: "- Tamanho único (P/M/G)",
    price: 44.99,
    images: ["/images/body-nude.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#ebc8b2"],
    isNew: true,
    stock: 0,
    },
    {
    id: "25",
    name: "Vestido Floral",
    description: "- Tecido leve e confortável\n- Tamanho único (P/M/G)",
    price: 84.99,
    images: ["/images/vestidofloral.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#FFFFFF"],
    isNew: true,
    stock: 0, 
    },
    {
    id: "26",
    name: "Vestido Laço",
    description: "- Tecido leve e confortável\n- Tamanho único (P/M/G)",
    price: 89.99,
    images: ["/images/vestidolaço.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#ebc8b2"],
    isNew: true,
    stock: 0, 
    },
    {
    id: "27",
    name: "Saia plissada",
    description: "- Tecido leve e confortável\n- Tamanho único (P/M/G)",
    price: 69.99,
    images: ["/images/body-nude.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#ebc8b2"],
    isNew: true,
    stock: 0 
    },
    {
    id: "28",
    name: "Vestido Laura - Rosa",
    description: "",
    price: 94.99,
    images: ["/images/vestidolaura1.jpg"], 
    category: "Vestuario",
    sizes: ["M"],
    colors: ["#FF69B4"],
    isNew: true,
    stock: 0, 
    },
    {
    id: "29",
    name: "Vestido Melissa",
    description: "- Tamanho único (P/M/G)",
    price: 79.99,
    images: ["/images/vestidomelissa.jpg","/images/vestidomelissa1.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#0000FF"],
    isNew: true,
    stock: 0, 
    },
    {
    id: "30",
    name: "Saia Dunna",
    description: "- Tamanho único (P/M/G)", 
    price: 49.99,
    images: ["/images/saiabranca.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#FFFFFF"],
    isNew: true,
    stock: 0, 
    },
    {
    id: "31",
    name: "Saia Balonê Linho",
    description: "- Tamanho único (P/M/G)\n", 
    price: 29.99,
    images: ["/images/saialinho.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#000000"],
    isNew: true,
    stock: 1, 
    },
    {
    id: "32",
    name: "Body Cavado",
    description: "- Tamanho único (P/M/G)\n", 
    price: 29.99,
    images: ["/images/bodycinza.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#808080"],
    isNew: true,
    stock: 1, 
    },
    {
    id: "33",
    name: "Short Saia Couro",
    description: "- Tamanho (M)\n", 
    price: 49.99,
    images: ["/images/saiacouro.jpg"], 
    category: "Vestuario",
    sizes: ["M"],
    colors: ["#000000"],
    isNew: true,
    stock: 1, 
    },
    {
    id: "34",
    name: "Vestido Verão ",
    description: "- Tamanho único (P/M/G)\n", 
    price: 69.99,
    images: ["/images/vestidoverde.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors: ["#5be90eff"],
    isNew: true,
    stock: 1, 
    },
    {
    id: "35",
    name: "Saia com detalhe de laço",
    description: "- Tamanho único (P/M/G)\n", 
    price: 59.99,
    images: ["/images/saialaço.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors:["#ffffffff"],
    isNew: true,
    stock: 0, 
    },
    {
    id: "36",
    name: "Body Branco",
    description: "- Tamanho único (P/M/G)\n", 
    price: 44.99,
    images: ["/images/bodybranco1.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors:["#ffffffff"],
    isNew: true,
    stock: 1, 
    },
    {
    id: "37",
    name: "Body Cinza",
    description: "- Tamanho único (P/M/G)\n", 
    price: 44.99,
    images: ["/images/bodycinza1.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors:["#808080"],
    isNew: true,
    stock: 1, 
    },
    {
    id: "38",
    name: "Cropped batinha",
    description: "- Tamanho único (P/M/G)\n", 
    price: 49.99,
    images: ["/images/croppedbatinha.jpg"], 
    category: "Vestuario",
    sizes: ["U"],
    colors:["#FFFFFF"],
    isNew: true,
    stock: 0, 
    },
    
];  